// Date: 8/5/2013 1:55:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModelBuoy extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Shape1;
    ModelRenderer TopBase;
    ModelRenderer CornorPole2;
    ModelRenderer CornorPole1;
    ModelRenderer CornorPole1;
    ModelRenderer CornorPole1;
  
  public ModelModelBuoy()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 16, 6, 16);
      Base.setRotationPoint(-8F, 18F, -8F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 22);
      Shape1.addBox(0F, 0F, 0F, 2, 20, 2);
      Shape1.setRotationPoint(-1F, -2F, -1F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      TopBase = new ModelRenderer(this, 8, 22);
      TopBase.addBox(0F, 0F, 0F, 10, 6, 10);
      TopBase.setRotationPoint(-5F, -8F, -5F);
      TopBase.setTextureSize(64, 64);
      TopBase.mirror = true;
      setRotation(TopBase, 0F, 0F, 0F);
      CornorPole2 = new ModelRenderer(this, 0, 22);
      CornorPole2.addBox(-1F, 0F, 0F, 2, 21, 2);
      CornorPole2.setRotationPoint(4F, -2F, -5F);
      CornorPole2.setTextureSize(64, 64);
      CornorPole2.mirror = true;
      setRotation(CornorPole2, -0.0698132F, 0F, -0.0698132F);
      CornorPole1 = new ModelRenderer(this, 0, 22);
      CornorPole1.addBox(0F, 0F, 0F, 2, 21, 2);
      CornorPole1.setRotationPoint(3F, -2F, 3F);
      CornorPole1.setTextureSize(64, 64);
      CornorPole1.mirror = true;
      setRotation(CornorPole1, 0.0872665F, 0F, -0.0872665F);
      CornorPole1 = new ModelRenderer(this, 0, 22);
      CornorPole1.addBox(0F, 0F, 0F, 2, 21, 2);
      CornorPole1.setRotationPoint(-5F, -2F, 3F);
      CornorPole1.setTextureSize(64, 64);
      CornorPole1.mirror = true;
      setRotation(CornorPole1, 0.0872665F, 0F, 0.0872665F);
      CornorPole1 = new ModelRenderer(this, 0, 22);
      CornorPole1.addBox(0F, 0F, 0F, 2, 21, 2);
      CornorPole1.setRotationPoint(-5F, -3F, -5F);
      CornorPole1.setTextureSize(64, 64);
      CornorPole1.mirror = true;
      setRotation(CornorPole1, -0.0872665F, 0F, 0.0872665F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Shape1.render(f5);
    TopBase.render(f5);
    CornorPole2.render(f5);
    CornorPole1.render(f5);
    CornorPole1.render(f5);
    CornorPole1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
